### ISSUE TITLE
map tile highlight "jiggles" during fine movements

### ISSUE THREAD

**Issue by crector** [chuckrector/mappo#1]
i need to understand the math here a lot better. it's proving to be a little tricky. regardless of zoom level, it will jiggle by one canvas pixel.

see inside `middlePanel`'s `mousemove` handler:

```javascript
  if (state.selectedTileLayerIndex !== -1) {
    const layer = state.map.tileLayers[state.selectedTileLayerIndex]
    const tileWidth = tileset.tileWidth
    const tileHeight = tileset.tileHeight
    const scaleX = ~~(event.offsetX / scale)
    const scaleY = ~~(event.offsetY / scale)
    const parallaxX = ~~(state.camera.x * layer.parallax.x)
    const parallaxY = ~~(state.camera.y * layer.parallax.y)
    const x = scaleX - ((parallaxX + scaleX) % tileWidth)
    const y = scaleY - ((parallaxY + scaleY) % tileHeight)

    if (x !== state.highlightedMapTile.x || y !== state.highlightedMapTile.y) {
      store.dispatch({type: `HIGHLIGHT_MAP_TILE`, x, y})
    }
  }
```

happens regardless of `~~` truncation. note that `renderLayer` performs `~~` truncation, since rendering is faster at whole-pixel boundaries.

**Comment by chuckrector** [comment]
i solved this by reducing down to tile x/y in redux state, then translating to px after map render. had to grab back some info about the selected layer's tile & pixel top left edge in order to line things up correctly. would love a simpler solution tho
